version: "3.8"

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    ports:
      - "5173:5173"
    command: yarn dev
    environment:
      - HOST=0.0.0.0 # localhost接続をする際に必要
      - CHOKIDAR_USEPOLLING=true # ホットリロードを可能にする
    volumes:
      - type: bind
        source: ./client/src
        target: /usr/app/src
      - type: volume
        source: dependencies
        target: /usr/app/node_modules
    depends_on:
      - server
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    ports:
      - 80:80
    volumes:
      - type: bind
        source: ./server/src
        target: /go/app/src
  redis:
    image: redis:7.0.2
    command: redis-server --appendonly yes
    restart: always
    ports:
      - 6379:6379
    volumes:
      - type: volume
        source: redis-volume
        target: /data

volumes:
  dependencies:
  redis-volume:
